name: 'simple-status-summary-from-rl-json'
description: 'A GitHub Action that builds a simple scan summary in simple-summsry.md from a report.rl.json file'

inputs:
  rl_json_file_path:
    description: 'the path to the report.rl.json'
    required: true

outputs:
  simple_summary_markdown:
    description: 'The path to the markdown summary file'
    value: ${{ steps.parse.outputs.simple_summary_markdown }}

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: parse the report.rl.json
      id: parse
      run: |
            name="simple_summary_markdown"
            out="${name}.md"
            inp=${{ inputs.rl_json_file_path }}
            python parse-rl-json-github.py ${inp} >${out}
            ls -l ${inp} ${out}
            echo "${name}=${out}" >> $GITHUB_OUTPUT
      shell: bash
