# .github/workflows/test_action.yaml
name: Test Action
on: [push, pull_request]

jobs:
  parse_rl_json:
    runs-on: ubuntu-latest
    name: parse a report.rl.json file

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # uses: ./ # Uses an action in the root directory
      # or use a released GitHub Action
      # uses: rl-maartenb/gh-make-comment-from-rl-json-test@v0.0.2
      - name: produce a output md file
        id: parse_test
        # uses: ./
        uses: rl-maartenb/gh-make-comment-from-rl-json-test@v0.0.2
        with:
          rl_json_file_path: 'tests/report.rl.json'

      - name: Print the outout file
        run: echo "${{ steps.parse_test.outputs.simple_summary_markdown }}"
